spring:
  application:
    name: eureka-server
  security:
    user:
      name: dmxiaoshen
      password: 123

server:
  port: 8888

eureka:
  instance:
    #单点eureka这个不能开启 会有一个http://localhost:8761/eureka/乱入
    #prefer-ip-address: true
    hostname: localhost
  client:
    #表示是否将自己注册到Eureka Server上，默认为true，当前应用为Eureka Server所以无需注册
    register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
    fetch-registry: false
