server:
  port: 8086
spring:
  application:
     name: spring-boot-activiti6
  datasource:
    url: jdbc:mysql://localhost:3306/activiti_6?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
      # \u81EA\u52A8\u90E8\u7F72\u9A8C\u8BC1\u8BBE\u7F6E:true-\u5F00\u542F\uFF08\u9ED8\u8BA4\uFF09\u3001false-\u5173\u95ED
      check-process-definitions: false
      #\u81EA\u52A8\u90E8\u7F72\u6587\u4EF6\u8DEF\u5F84\u540E\u7F00
  #   process-definition-location-prefix: classpath:/processes/
  #   process-definition-location-suffixes:
  #      - **.bpmn
  #      - **.bpmn20.xml