spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  second-datasource:
#    jdbc-url: jdbc:mysql://localhost:3306/spring_boot_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mappers/*Dao.xml
server:
  port: 8081
